In [1]:
import pandas as pd

In [4]:
def selectData(students):
    result = students[students['student_id'] == 101][['name', 'age']]
    return result

In [5]:
# Пример DataFrame
data = {
    'student_id': [101, 53, 128, 3],
    'name': ['Ulysses', 'William', 'Henry', 'Henry'],
    'age': [13, 10, 6, 11]
}

students = pd.DataFrame(data)

# Вызываем функцию для получения имени и возраста студента с student_id = 101
result = selectData(students)
print(result)

      name  age
0  Ulysses   13